# Generated by Django 5.1.11 on 2025-08-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockquote',
            managers=[
            ],
        ),
    ]
